### ISSUE TITLE
ESPHome/ESP32 version

### ISSUE THREAD

**Issue by nervous-inhuman** [lamperez/xiaomi-lightbar-nrf24#1]
Hi,

first of all, wonderful project, thanks for taking the time and effort to look into this device.
I will try to set it up to test it out on my spare RPi device.

However, because the project is written specifically with the pyRF24 library, I probably won't be able to use it on my installation of Home Assistant, which is virtualized on a x86 device. 

I was looking into using a serial converter like a CH341 to be able to interface with an NRF24 on a non-RPi device, however, I realised that probably the most convinient solution would be to use a device such as ESP32 with the ESPHome project.

Alternatively, maybe you could add MQTT to the current project, so one could have a spare RPi as "gateway"? 

What are your thoughts on this? 

Thanks!

**Comment by lamperez** [comment]
Thanks!

Yes, the binary dependencies for the pyRF24 library are the main limitation. My Home Assistant runs in a container, and I have to build an ad-hoc image just for them.
 
I have a rather primitive, version of an Arduino-based solution, that I used for tests. My original idea was to put it in an ESP32 and make it a bridge to MQTT (I have other projects with MQTT control), and/or to implement a simple web server to control the thing through GET requests. I have some NRF24L01 laying around, so when I have some spare time (soon, I hope) I will clean the code, test it, and publish it here.

**Comment by ceear** [comment]
> Thanks!
> 
> Yes, the binary dependencies for the pyRF24 library are the main limitation. My Home Assistant runs in a container, and I have to build an ad-hoc image just for them.
> 
> I have a rather primitive, version of an Arduino-based solution, that I used for tests. My original idea was to put it in an ESP32 and make it a bridge to MQTT (I have other projects with MQTT control), and/or to implement a simple web server to control the thing through GET requests. I have some NRF24L01 laying around, so when I have some spare time (soon, I hope) I will clean the code, test it, and publish it here.

Sorry for commenting on an already closed topic, but could you share your current (albeit untested) code? I'm looking into the same esp32 option and dont like the idea of "reinventing the wheel".

Thank you

**Comment by deffuseyou** [comment]
> I have a rather primitive, version of an Arduino-based solution, that I used for tests. My original idea was to put it in an ESP32 and make it a bridge to MQTT (I have other projects with MQTT control), and/or to implement a simple web server to control the thing through GET requests. I have some NRF24L01 laying around, so when I have some spare time (soon, I hope) I will clean the code, test it, and publish it here.

Hello, I would also like to implement for esp8266 based microcontroller, could you please share the developments? I already got the device_id for my lamp.

**Comment by rossiluis22** [comment]
Having it on a ESP32 would be awesome, bc I run HA in a docker mini-pc X86 and having a RPI running just for this is a lot of waste 😞, thanks I'm advance

**Comment by frostworx** [comment]
This project is great, but I'd love to control the light using esphome as well.
May I ask if it was intentional that this issue was closed after replying?

**Comment by ebinf** [comment]
While I didn't do a ESPHome integration (yet), I've built a version for ESP32 based on the insights of this repository. Maybe that's already what you're looking for: https://github.com/ebinf/lightbar2mqtt
