### ISSUE TITLE
Unable to control Lightbar with the correct ID

### ISSUE THREAD

**Issue by ersonp** [lamperez/xiaomi-lightbar-nrf24#3]
Hi, first of all, amazing work with the project. I am running into some issues and I hope you will be able to help me with it. I am running this project on a 
- Raspberry Pi Zero 2 w  
- running Python 3.9.2 
- with a nRF24L01(+) module 
- and I have a Xiaomi My Computer Monitor Light Bar, model MJGJD01YL (without BLE or app).

After about 3-4 hours of trying I was able to catch 2 packets with the correct crc with the provided script
```
================ SPI Configuration ================
CSN Pin         = /dev/spidev0.0
CE Pin          = Custom GPIO25
SPI Speedz      = 10 Mhz
================ NRF Configuration ================
STATUS          = 0x0e RX_DR=0 TX_DS=0 MAX_RT=0 RX_P_NO=7 TX_FULL=0
RX_ADDR_P0-1    = 0x5555555555 0x533914dd1c
RX_ADDR_P2-5    = 0xc3 0xc4 0xc5 0xc6
TX_ADDR         = 0x5555555555
RX_PW_P0-6      = 0x0c 0x0c 0x0c 0x0c 0x0c 0x0c
EN_AA           = 0x3f
EN_RXADDR       = 0x02
RF_CH           = 0x44
RF_SETUP        = 0x0b
CONFIG          = 0x03
DYNPD/FEATURE   = 0x00 0x00
Data Rate       = 2 MBPS
Model           = nRF24L01+
CRC Length      = 8 bits
PA Power        = PA_LOW
ARC             = 0

Decoded packet, CRC ok
• id: 0xa2c231
• separator: 0xff
• counter: 0x95
• command: 0x5fe
• crc: 0xbe5

Decoded packet, CRC ok
• id: 0xa2c231
• separator: 0xff
• counter: 0x43
• command: 0x401
• crc: 0xf110
```
but I am unable to control the Lighbar by using the ID in the example given in the [readme](https://github.com/lamperez/xiaomi-lightbar-nrf24/tree/main?tab=readme-ov-file#usage)

**Comment by lamperez** [comment]
Thank you!

If you have captured not one but two packets I am pretty sure that your hardware works and the capture id is correct. But several hours is too much, I usually catch one packet each ten or fifteen seconds, while turning the remote wheel. Maybe the channel you are using is too noisy, or the received power too low. 

It seems that you are using channel 68 = 0x44, and I suppose that you have tried others. Anyway, the channels that work are 6, 7, 15, 16, 43, 44, 68, 69 (I have discovered 15 and 16 just now). BTW, if anyone else reads this, you can change the channel like this
```python
bar = Lightbar(0, 25, 0x123456)
bar.radio.channel = 43
bar.on_off()
```

Also, you may try increasing the transmitted power, 
```python
import pyrf24
bar.radio.pa_level = pyrf24.RF24_PA_MIN
bar.radio.pa_level = pyrf24.RF24_PA_LOW  # <-- Default
bar.radio.pa_level = pyrf24.RF24_PA_HIGH
bar.radio.pa_level = pyrf24.RF24_PA_MAX
```
Or just edit the values in `radio.py`.

**Comment by lamperez** [comment]
And another note: you can control the bar even if you do not know the remote id. Just use an arbitrary code
```python
bar = Lightbar(25, 0, 0x111111)
```
Then unplug and plug the bar, and within 20 seconds run
```python
bar.reset()
```
to reprogram the bar with your new code. ~~I should write this in the readme.~~

Of course, now the remote will not work anymore. You can undo this by unplugging and plugging the bar again, and long pressing the remote (this procedure is in the lightbar manual).

**Comment by ersonp** [comment]
The correct packet capturing probably is a power issue as I am powering the module directly via the RPi. I will test again with an external power source for the NRF module once I get my hands on the needed parts. In my current setup, I couldn't quickly capture the correct packet with any of these combinations.

| chnl / pwr lvl | 6 | 7 | 15 | 16 | 43 | 44 | 68 | 69 |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| min | wrong crc | no resp | wrong crc | no resp | wrong crc | no resp | wrong crc | no resp |
| low | wrong crc | no resp | wrong crc | no resp | wrong crc | no resp | wrong crc | no resp |
| high | wrong crc | no resp | wrong crc | no resp | wrong crc | no resp | wrong crc | no resp |
| max | wrong crc | no resp | wrong crc | no resp | wrong crc | no resp | wrong crc | no resp |

As for how to control the light with the NRF module part, previously I gave up after trying 2-3 channels. But after trying all the combinations I was able to find a few that do work pretty regularly.


| pwr / chnl  | 6 | 7 | 15 | 16 | 43 | 44 | 68 | 69 |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| min | no | no | no | weak | no | no | no | no |
| low | no | no | very weak | no | yes | yes | no | no |
| high | no | no | no | yes | yes | yes | very weak | very weak |
| max | no | no | yes | yes | weak | no | yes | no |


I have updated the scan script to take in the power level and the channel as a cmd argument. As well as created a new script to test the lightbar once the correct ID is obtained. If you don't mind, I can create a PR for it.

**Comment by ersonp** [comment]
Update: Just in case someone else is trying this in the future. I was able to fix the power issue by using [this](https://www.aliexpress.com/i/1911831179.html) adapter board for the nRF24 and using the 5v pin from the RPi instead of the 3.3v. For more info about the adapter board check [this video](https://www.youtube.com/watch?v=57pdX6b0sfw). You can play around with the power setting till you can find the correct packet (eg: PA_HIGH, PA_MAX).

![image](https://github.com/lamperez/xiaomi-lightbar-nrf24/assets/38801159/f6fc8939-6561-4d36-95f0-32e460e41179)
(image for reference just in case the URL becomes invalid in the future)
