### ISSUE TITLE
boost.python is not required to build pyrf24 from source

### ISSUE THREAD

**Issue by 2bndy5** [lamperez/xiaomi-lightbar-nrf24#8]
I just noticed some inaccurate (or outdated) advice in the README:
https://github.com/lamperez/xiaomi-lightbar-nrf24/blob/2cb59e6eca7e2fab629233b6e243c97d6d2cd97d/readme.md?plain=1#L38-L51

The README should be updated like so:
~~~diff
 ## Dependencies 
 
-- `pyrf24` [RF24 python library](https://nrf24.github.io/RF24)
+- `pyrf24` [pyRF24 python library](https://nrf24.github.io/pyRF24)
 - `crc` [CRC python library](https://github.com/Nicoretti/crc) 
  
-Notice that `pyrf24` may need to build some dynamic libraries. So, you will need some additional 
-packages:
+Notice that `pyrf24` may need to build from source on some systems.
+In such case, you will need cmake and python headers (python3-dev) installed.
  
 - Debian based OS (e.g. Raspberry Pi OS) 
 ```sh 
-  sudo apt-get install python3-dev libboost-python-dev 
+  sudo apt-get install python3-dev cmake
   python -m pip install pyrf24 
-
 ```
~~~

If installing on a 64-bit Linux, then building from source is only necessary if using PyPy or when using [musl](https://en.wikipedia.org/wiki/Musl) instead of GNU C. Installing on a 32-bit system will likely need to build from source, especially if not using the RPi OS 32-bit. The [piwheels project does provide 32-bit builds](https://www.piwheels.org/project/pyrf24/), but they explicitly only support RPi OS 32-bit.

### Some history
The boost.python library was only used in the older individual python wrappers (still) provided with each RF24* repository. The pyrf24 project changed that by replacing boost.python with pybind11. Users do not need to install pybind11 as it is included in the pyrf24 source distribution.

All binaries built for the pyrf24 package are isolated to the python env used, so the RF24 C++ libs and boost.python are not required to be installed separately. Those are only prerequisites for the older individual python wrappers.

**Comment by lamperez** [comment]
Thank you, I have updated the README.
